---
######################### Playbook just to configure k8s cluster on any number of nodes
### The cluster components
####                    1- 1x K8S adm
###                     2- nx K8S computing nodes
### roles/init_env : 
#               Written by : Ahmed M. Elsayed: compiler@aast.edu
#   All k8s cluster setup written by bsder, URL: https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-cluster-using-kubeadm-on-ubuntu-18-04
#   1-Convert all playbooks into roles
#   Tweams:
#               1-Remove the kube* versions from installation
#               2-Add docker handler, and notified to start
#               3-Add task enable docker
#               4-Add when clause to all kubeadmin settings to limit its execution to cluster admin only
#               5-Fixing the url for flannel pod 
#               6-Fixing docker daemon to systemd (https://kubernetes.io/docs/setup/production-environment/container-runtimes/)

- name: Install and configure K8S Cluster
  hosts: all
  become: yes
  gather_facts: no
  roles:
          - roles/init_env
          - roles/initial
          - roles/kube-dependencies
          - role: roles/kube-dependencies-adm
            when: inventory_hostname in groups['clusteradmin']
          - role: roles/configmaster
            when: inventory_hostname in groups['clusteradmin']
          - role: roles/configworker

